// <auto-generated />
using System;
using EGID.Test.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EGID.Test.API.Migrations
{
    [DbContext(typeof(EGIDDbContext))]
    [Migration("20220914185948_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EGID.Test.API.Data.Entities.Broker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Brokers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Broker1"
                        });
                });

            modelBuilder.Entity("EGID.Test.API.Data.Entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrokerId")
                        .HasColumnType("int");

                    b.Property<double>("Commission")
                        .HasColumnType("float");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BrokerId");

                    b.HasIndex("PersonID");

                    b.HasIndex("StockID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EGID.Test.API.Data.Entities.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BrokerId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BrokerId = 1,
                            Name = "Client1"
                        },
                        new
                        {
                            ID = 2,
                            BrokerId = 1,
                            Name = "Client2"
                        });
                });

            modelBuilder.Entity("EGID.Test.API.Data.Entities.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Vianet",
                            Price = 61.0
                        },
                        new
                        {
                            ID = 2,
                            Name = "Agritek",
                            Price = 96.0
                        },
                        new
                        {
                            ID = 3,
                            Name = "Akamai",
                            Price = 56.0
                        },
                        new
                        {
                            ID = 4,
                            Name = "Baidu",
                            Price = 57.0
                        },
                        new
                        {
                            ID = 5,
                            Name = "Blinkx",
                            Price = 78.0
                        },
                        new
                        {
                            ID = 6,
                            Name = "Blucora",
                            Price = 75.0
                        },
                        new
                        {
                            ID = 7,
                            Name = "Boingo",
                            Price = 93.0
                        },
                        new
                        {
                            ID = 8,
                            Name = "Brainybrawn",
                            Price = 89.0
                        },
                        new
                        {
                            ID = 9,
                            Name = "Carbonite",
                            Price = 73.0
                        },
                        new
                        {
                            ID = 10,
                            Name = "China Finance",
                            Price = 69.0
                        },
                        new
                        {
                            ID = 11,
                            Name = "ChinaCache",
                            Price = 77.0
                        },
                        new
                        {
                            ID = 12,
                            Name = "ADR",
                            Price = 51.0
                        },
                        new
                        {
                            ID = 13,
                            Name = "ChitrChatr",
                            Price = 92.0
                        },
                        new
                        {
                            ID = 14,
                            Name = "Cnova",
                            Price = 56.0
                        },
                        new
                        {
                            ID = 15,
                            Name = "Cogent",
                            Price = 76.0
                        },
                        new
                        {
                            ID = 16,
                            Name = "Crexendo",
                            Price = 84.0
                        },
                        new
                        {
                            ID = 17,
                            Name = "CrowdGather",
                            Price = 66.0
                        },
                        new
                        {
                            ID = 18,
                            Name = "EarthLink",
                            Price = 70.0
                        },
                        new
                        {
                            ID = 19,
                            Name = "Eastern",
                            Price = 69.0
                        },
                        new
                        {
                            ID = 20,
                            Name = "ENDEXX",
                            Price = 53.0
                        },
                        new
                        {
                            ID = 21,
                            Name = "Envestnet",
                            Price = 62.0
                        },
                        new
                        {
                            ID = 22,
                            Name = "Epazz",
                            Price = 86.0
                        },
                        new
                        {
                            ID = 23,
                            Name = "FlashZero",
                            Price = 80.0
                        },
                        new
                        {
                            ID = 24,
                            Name = "Genesis",
                            Price = 94.0
                        },
                        new
                        {
                            ID = 25,
                            Name = "InterNAP",
                            Price = 64.0
                        },
                        new
                        {
                            ID = 26,
                            Name = "MeetMe",
                            Price = 99.0
                        },
                        new
                        {
                            ID = 27,
                            Name = "Netease",
                            Price = 98.0
                        },
                        new
                        {
                            ID = 28,
                            Name = "Qihoo",
                            Price = 76.0
                        });
                });

            modelBuilder.Entity("EGID.Test.API.Data.Entities.Order", b =>
                {
                    b.HasOne("EGID.Test.API.Data.Entities.Broker", "Broker")
                        .WithMany("Orders")
                        .HasForeignKey("BrokerId");

                    b.HasOne("EGID.Test.API.Data.Entities.Person", "Person")
                        .WithMany("Orders")
                        .HasForeignKey("PersonID");

                    b.HasOne("EGID.Test.API.Data.Entities.Stock", "Stock")
                        .WithMany("orders")
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGID.Test.API.Data.Entities.Person", b =>
                {
                    b.HasOne("EGID.Test.API.Data.Entities.Broker", "Broker")
                        .WithMany("Clients")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
